---
# tasks file for jpnewman.elk-logstash-indexer
- name: Import Elastic GPG Key
  apt_key: url="{{ elasticsearch_gpg_key_url }}" state=present

- name: Add Logstash Repo into source list
  apt_repository:
    repo: "{{ logstash_apt_repository }}"
#    filename: logstash
    state: present
    update_cache: yes

- name: Install Logstash
  apt:
    name: logstash
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify: restart logstash

- name: Config Upstart
  template:
    src: upstart/logstash.j2
    dest: /etc/default/logstash
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

# SSL Cert
- name: Create directory to store ssl crt & key
  tags: ["ssl"]
  file: path={{ ssl_cert_directory }} state=directory

- name: Copy SSL cert
  tags: ["ssl"]
  copy: src={{ ssl_cert_local_directory }}/{{ ssl_cert }} dest={{ ssl_cert_directory }}
  notify: restart logstash

- name: Copy SSL key
  tags: ["ssl"]
  copy: src={{ ssl_cert_local_directory }}/{{ ssl_key }} dest={{ ssl_cert_directory }}
  notify: restart logstash

# Config
- name: Copy indexer templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: logstash
    group: logstash
    mode: 0644
  with_items:
     - { src: 'logstash/conf.d/01-redis-input.conf.j2', dest: '/etc/logstash/conf.d/01-redis-input.conf' }
     - { src: 'logstash/conf.d/02-topbeat-input.conf.j2', dest: '/etc/logstash/conf.d/02-topbeat-input.conf' }
     - { src: 'logstash/conf.d/30-elasticsearch-output.conf.j2', dest: '/etc/logstash/conf.d/30-elasticsearch-output.conf' }
  notify:
    - restart logstash

- name: Copy shipper debug templates, if needed
  template:
    src: logstash/conf.d/31-stdout-output.conf.j2
    dest: /etc/logstash/conf.d/31-stdout-output.conf
    owner: logstash
    group: logstash
    mode: 0644
  when: logstash_debug
  notify:
    - restart logstash

- name: Remove shipper debug templates, if needed
  file: path=/etc/logstash/conf.d/31-stdout-output.conf state=absent
  when: not logstash_debug
  notify:
    - restart logstash

- name: Check logstash config
  become: yes
  command: /usr/share/logstash/bin/logstash -t -f /etc/logstash/conf.d --path.settings=/etc/logstash/
  register: result
  when: check_logstash_config
  changed_when: False
